# Generated by Django 5.2.5 on 2025-09-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Service image for cards', null=True, upload_to='services/images/'),
        ),
        migrations.AddField(
            model_name='service',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', help_text='Choose whether to display image or video', max_length=10),
        ),
        migrations.AddField(
            model_name='service',
            name='video',
            field=models.FileField(blank=True, help_text='Service video for cards (MP4, WebM, etc.)', null=True, upload_to='services/videos/'),
        ),
    ]
