# Generated by Django 5.2.5 on 2025-09-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_image_service_media_type_service_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='specialized_solutions',
            field=models.TextField(blank=True, help_text='Detailed specialized solutions and features for this service', null=True),
        ),
    ]
