# Generated by Django 5.2.5 on 2025-08-31 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('project_interest', models.CharField(choices=[('WEB_DEV', 'Website Development'), ('MOBILE_APP', 'Mobile App Development'), ('MARKETING', 'Digital Marketing'), ('DESIGN', 'UI/UX Design'), ('CONSULTING', 'IT Consulting')], max_length=20)),
                ('message', models.TextField()),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('consent_to_store', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-submission_date'],
            },
        ),
    ]
