# Generated by Django 5.2.5 on 2025-08-31 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ECOMMERCE', 'E-commerce'), ('MOBILE_APP', 'Mobile App'), ('FINTECH', 'FinTech'), ('WEB_APP', 'Web Application'), ('MARKETING', 'Digital Marketing')], max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/images/')),
                ('date_delivered', models.DateField()),
                ('project_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_provided', models.ManyToManyField(related_name='projects', to='services.service')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-date_delivered'],
            },
        ),
    ]
