# Generated by Django 5.2.5 on 2025-08-31 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='testimonial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_projects', to='testimonials.testimonial'),
        ),
    ]
