# Generated by Django 5.2.5 on 2025-09-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_logo',
            field=models.ImageField(blank=True, help_text='Logo of the client company', null=True, upload_to='projects/client_logos/'),
        ),
    ]
